/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-pressed': 'var(--primary-pressed)',
        'primary-deep': 'var(--primary-deep)',
        navy: 'var(--brand-navy)',
        'navy-deep': 'var(--brand-navy-deep)',
        'link-blue': 'var(--link-blue)',
        canvas: 'var(--canvas)',
        surface: 'var(--surface)',
        'surface-soft': 'var(--surface-soft)',
        hairline: 'var(--hairline)',
        'hairline-soft': 'var(--hairline-soft)',
        'hairline-strong': 'var(--hairline-strong)',
        'ink-deep': 'var(--ink-deep)',
        ink: 'var(--ink)',
        charcoal: 'var(--charcoal)',
        slate: 'var(--slate)',
        steel: 'var(--steel)',
        stone: 'var(--stone)',
        muted: 'var(--muted)',
        'tint-peach': 'var(--tint-peach)',
        'tint-rose': 'var(--tint-rose)',
        'tint-mint': 'var(--tint-mint)',
        'tint-lavender': 'var(--tint-lavender)',
        'tint-sky': 'var(--tint-sky)',
        'tint-yellow': 'var(--tint-yellow)',
        'tint-yellow-bold': 'var(--tint-yellow-bold)',
        'tint-cream': 'var(--tint-cream)',
        'tint-gray': 'var(--tint-gray)',
        'brand-pink': 'var(--brand-pink)',
        'brand-orange': 'var(--brand-orange)',
        'brand-orange-deep': 'var(--brand-orange-deep)',
        'brand-green': 'var(--brand-green)',
        'brand-purple-800': 'var(--brand-purple-800)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: 'var(--error)',
        'error-tint': 'var(--error-tint)',
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '20px',
      },
      boxShadow: {
        s1: 'rgba(15,15,15,0.04) 0 1px 2px 0',
        s2: 'rgba(15,15,15,0.08) 0 4px 12px 0',
        s3: 'rgba(15,15,15,0.20) 0 24px 48px -8px',
        s4: 'rgba(15,15,15,0.16) 0 16px 48px -8px',
      },
      fontFamily: {
        sans: ['Inter', 'Notion Sans', '-apple-system', 'system-ui', 'Segoe UI', 'Helvetica', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
