/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-pressed': 'var(--primary-pressed)',
        'primary-deep': 'var(--primary-deep)',
        navy: 'var(--brand-navy)',
        'navy-deep': 'var(--brand-navy-deep)',
        'wood-walnut': 'var(--wood-walnut)',
        'wood-walnut-deep': 'var(--wood-walnut-deep)',
        'wood-saddle': 'var(--wood-saddle)',
        'wood-oak': 'var(--wood-oak)',
        'link-blue': 'var(--link-blue)',
        canvas: 'var(--canvas)',
        surface: 'var(--surface)',
        'surface-soft': 'var(--surface-soft)',
        hairline: 'var(--hairline)',
        'hairline-soft': 'var(--hairline-soft)',
        'hairline-strong': 'var(--hairline-strong)',
        'ink-deep': 'var(--ink-deep)',
        ink: 'var(--ink)',
        charcoal: 'var(--charcoal)',
        slate: 'var(--slate)',
        steel: 'var(--steel)',
        stone: 'var(--stone)',
        muted: 'var(--muted)',
        'tint-peach': 'var(--tint-peach)',
        'tint-rose': 'var(--tint-rose)',
        'tint-mint': 'var(--tint-mint)',
        'tint-lavender': 'var(--tint-lavender)',
        'tint-sky': 'var(--tint-sky)',
        'tint-yellow': 'var(--tint-yellow)',
        'tint-yellow-bold': 'var(--tint-yellow-bold)',
        'tint-cream': 'var(--tint-cream)',
        'tint-gray': 'var(--tint-gray)',
        'brand-pink': 'var(--brand-pink)',
        'brand-orange': 'var(--brand-orange)',
        'brand-orange-deep': 'var(--brand-orange-deep)',
        'brand-green': 'var(--brand-green)',
        'brand-purple-800': 'var(--brand-purple-800)',
        wine: 'var(--primary)',
        terracotta: 'var(--brand-orange)',
        olive: 'var(--brand-green)',
        saffron: 'var(--brand-yellow)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: 'var(--error)',
        'error-tint': 'var(--error-tint)',
      },
      borderRadius: {
        xs: '2px',
        sm: '3px',
        md: '4px',
        lg: '6px',
        xl: '10px',
        xxl: '14px',
      },
      boxShadow: {
        s1: 'rgba(42,24,16,0.06) 0 1px 2px 0',
        s2: 'rgba(42,24,16,0.12) 0 4px 14px 0',
        s3: 'rgba(42,24,16,0.24) 0 24px 48px -8px',
        s4: 'rgba(42,24,16,0.20) 0 16px 48px -8px',
      },
      fontFamily: {
        display: ['Bodoni Moda', 'Playfair Display', 'Didot', 'Georgia', 'serif'],
        body: ['Cormorant Garamond', 'EB Garamond', 'Georgia', 'Times New Roman', 'serif'],
        caps: ['Cinzel', 'Trajan Pro', 'Georgia', 'serif'],
        sans: ['Cormorant Garamond', 'EB Garamond', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
}
